"""
app/routes/pdf_routes.py — SPECIAL PDF endpoints only.

The 36 standard PDF tool routes are generated by the universal route factory
(app/routes/tool_factory.py) from the catalog. This blueprint keeps only the
genuinely special endpoints that bypass the standard upload->pipeline->download
flow: the DOCX text-editor round-trip and the interactive canvas editor.
"""
import io
import json
import logging
import os
import shutil
import tempfile

from flask import Blueprint, request, jsonify, send_file

from app.controllers.job_controller import JobController
from config import Config
from core.exceptions import ValidationError
from core.result import Result
from services.file_service import file_service

pdf_bp = Blueprint("pdf", __name__, url_prefix="/api/pdf")
log = logging.getLogger("pdfwala.routes.pdf")


# ── Edit PDF (text-editor flow) ───────────────────────────────────────────────

@pdf_bp.route("/edit-text/load", methods=["POST"])
def edit_text_load():
    rl = JobController.check_rate_limit(request)
    if rl:
        return rl
    ctx = JobController.build_ctx(request, "edit_text_load")
    try:
        file_service.save_single(request, ctx, "file")
    except ValidationError as ex:
        return Result.error(ex.message, 400)
    try:
        from engines.pdf_edit_text import pdf_to_editor_html
        result = pdf_to_editor_html(ctx)
    except ValidationError as ex:
        return Result.error(ex.message, 400)
    except Exception as ex:
        return Result.error(f"Could not prepare editor: {ex}", 500, ctx.job_id)
    return result


@pdf_bp.route("/edit-text/save", methods=["POST"])
def edit_text_save():
    rl = JobController.check_rate_limit(request)
    if rl:
        return rl
    ctx = JobController.build_ctx(request, "edit_text_save")
    try:
        from engines.pdf_edit_text import editor_html_to_pdf
        result = editor_html_to_pdf(ctx, request)
    except ValidationError as ex:
        return Result.error(ex.message, 400)
    except Exception as ex:
        return Result.error(f"Save failed: {ex}", 500, ctx.job_id)
    return result


# ── Canvas Editor (visual in-place text editing) ─────────────────────────────

_CANVAS_MAX_UPLOAD  = 50 * 1024 * 1024   # 50 MB
_CANVAS_MAX_CHANGES = 5000
_CANVAS_MAX_TEXTLEN = 2000


def _canvas_take_upload():
    """Save the uploaded PDF to TEMP_FOLDER with a 50 MB cap.
    Returns (path, None) on success or (None, error_response)."""
    f = request.files.get("file")
    if not f or not f.filename:
        return None, Result.error("No file uploaded (field='file')", 400)
    if (request.content_length or 0) > _CANVAS_MAX_UPLOAD:
        return None, Result.error(
            "File too large — the visual editor supports files up to 50 MB. "
            "Try Compress PDF first.", 413)
    fd, path = tempfile.mkstemp(suffix=".pdf", dir=Config.TEMP_FOLDER)
    os.close(fd)
    f.seek(0)
    with open(path, "wb") as out:
        shutil.copyfileobj(f, out, length=65536)
    size = os.path.getsize(path)
    if size == 0:
        os.remove(path)
        return None, Result.error("Uploaded file is empty", 400)
    if size > _CANVAS_MAX_UPLOAD:
        os.remove(path)
        return None, Result.error(
            "File too large — the visual editor supports files up to 50 MB. "
            "Try Compress PDF first.", 413)
    return path, None


@pdf_bp.route("/parse-canvas", methods=["POST"])
def parse_canvas():
    rl = JobController.check_rate_limit(request)
    if rl:
        return rl
    path, err = _canvas_take_upload()
    if err:
        return err
    try:
        from engines.pdf_engine import _parse_canvas_sync
        return jsonify(_parse_canvas_sync(path)), 200
    except ValidationError as ex:
        return Result.error(ex.message, 400)
    except Exception as ex:
        log.exception("parse-canvas failed")
        return Result.error(f"Could not read this PDF for editing: {ex}", 500)
    finally:
        try:
            os.remove(path)
        except OSError:
            pass


@pdf_bp.route("/save-canvas", methods=["POST"])
def save_canvas():
    rl = JobController.check_rate_limit(request)
    if rl:
        return rl
    path, err = _canvas_take_upload()
    if err:
        return err
    try:
        raw = request.form.get("changes", "")
        if not raw:
            return Result.error("No changes provided", 400)
        try:
            changes = json.loads(raw)
        except (TypeError, ValueError):
            return Result.error("changes is not valid JSON", 400)
        if not isinstance(changes, list) or not changes:
            return Result.error("No changes provided", 400)
        if len(changes) > _CANVAS_MAX_CHANGES:
            return Result.error(
                f"Too many edits ({len(changes)}); limit is {_CANVAS_MAX_CHANGES}.", 400)
        for ch in changes:
            if isinstance(ch, dict) and "new_text" in ch:
                ch["new_text"] = str(ch["new_text"])[:_CANVAS_MAX_TEXTLEN]
        scanned = str(request.form.get("scanned", "")).lower() in ("1", "true", "yes")

        from engines.pdf_engine import _save_canvas_sync
        pdf_bytes = _save_canvas_sync(path, changes, scanned=scanned)
        return send_file(
            io.BytesIO(pdf_bytes),
            mimetype="application/pdf",
            as_attachment=True,
            download_name="edited.pdf",
        )
    except ValidationError as ex:
        return Result.error(ex.message, 400)
    except Exception as ex:
        log.exception("save-canvas failed")
        return Result.error(f"Could not save your edited PDF: {ex}", 500)
    finally:
        try:
            os.remove(path)
        except OSError:
            pass
